### ISSUE TITLE
Reltime usage

### ISSUE THREAD

**Issue by JCavallo** [rhysd/accelerated-jk#4]
I noticed that accelerated-jk does not function properly using neovim. According to [this comment](https://github.com/neovim/neovim/issues/2567#issuecomment-101365135), it looks like the problem would be in the way the plugin handles `reltime` comparisons.

**Comment by rhysd** [comment]
So the problem is that the internal representation of time (which is returned from `reltime()`) is changed in NeoVim, right?

**Comment by JCavallo** [comment]
Yes and No. Neovim indeed has a slightly different result for `reltime`, but it is not inconsistant with `reltime` original (as in 'from vim') documentation. Here is a PR with an alternative, tested on vim and neovim.
